

export const LOCATIONS = [
  // Asia – Sea Ports & ICDs
  "Chennai Port, India",
  "Mumbai Port, India",
  "Tuticorin Port, India",
  "Cochin Port, India",
  "Kolkata Port, India",
  "Delhi ICD, India",
  "Bangalore ICD, India",
  "Hyderabad ICD, India",
  "Singapore Port, Singapore",
  "Dubai Port, UAE",
  "Jebel Ali Port, UAE",
  "Shanghai Port, China",
  "Shenzhen Port, China",
  "Hong Kong Port, Hong Kong",
  "Busan Port, South Korea",
  "Tokyo Port, Japan",
  "Kaohsiung Port, Taiwan",
  "Manila Port, Philippines",
  "Jakarta Port, Indonesia",
  "Bangkok Port, Thailand",
  "Ho Chi Minh City Port, Vietnam",
  "Colombo Port, Sri Lanka",
  "Karachi Port, Pakistan",
  "Dhaka Port, Bangladesh",
  "Yangon Port, Myanmar",
  "Kuala Lumpur Port, Malaysia",
  "Penang Port, Malaysia",
  "Surabaya Port, Indonesia",
  "Semarang Port, Indonesia",
  "Makassar Port, Indonesia",
  "Bandar Abbas Port, Iran",
  "Basra Port, Iraq",
  "Jeddah Port, Saudi Arabia",
  "Dammam Port, Saudi Arabia",
  "Salalah Port, Oman",
  "Muscat Port, Oman",
  "Abu Dhabi Port, UAE",
  "Fujairah Port, UAE",
  "Kuwait Port, Kuwait",
  "Bahrain Port, Bahrain",
  "Qatar Port, Qatar",
  "Doha Port, Qatar",
  "Riyadh ICD, Saudi Arabia",
  "Tehran Port, Iran",
  "Ashgabat Port, Turkmenistan",
  "Baku Port, Azerbaijan",
  "Tbilisi Port, Georgia",
  "Yerevan Port, Armenia",
  "Beirut Port, Lebanon",
  "Haifa Port, Israel",
  "Amman Port, Jordan",
  "Damascus Port, Syria",
  "Baghdad ICD, Iraq",
  "Ankara Port, Turkey",
  "Istanbul Port, Turkey",
  "Izmir Port, Turkey",
  "Alexandria Port, Egypt",
  "Port Said Port, Egypt",
  "Suez Port, Egypt",
  "Cairo ICD, Egypt",
  "Tripoli Port, Libya",
  "Benghazi Port, Libya",
  "Tunis Port, Tunisia",
  "Algiers Port, Algeria",
  "Oran Port, Algeria",
  "Casablanca Port, Morocco",
  "Tangier Port, Morocco",
  "Rabat Port, Morocco",
  "Cape Town Port, South Africa",
  "Durban Port, South Africa",
  "Johannesburg ICD, South Africa",
  "Maputo Port, Mozambique",
  "Beira Port, Mozambique",
  "Dar es Salaam Port, Tanzania",
  "Mombasa Port, Kenya",
  "Nairobi ICD, Kenya",
  "Djibouti Port, Djibouti",
  "Addis Ababa ICD, Ethiopia",
  "Khartoum Port, Sudan",
  "Port Sudan, Sudan",
  "Eritrea Port, Eritrea",
  "Mogadishu Port, Somalia",
  "Hargeisa ICD, Somalia",
  "Lagos Port, Nigeria",
  "Port Harcourt Port, Nigeria",
  "Abuja ICD, Nigeria",
  "Accra Port, Ghana",
  "Tema Port, Ghana",
  "Takoradi Port, Ghana",
  "Cotonou Port, Benin",
  "Lome Port, Togo",
  "Ouagadougou ICD, Burkina Faso",
  "Bamako ICD, Mali",
  "Dakar Port, Senegal",
  "Nouakchott Port, Mauritania",
  "Conakry Port, Guinea",
  "Freetown Port, Sierra Leone",
  "Monrovia Port, Liberia",
  "Abidjan Port, Ivory Coast",
  "San Pedro Port, Ivory Coast",
  "Yamoussoukro ICD, Ivory Coast",
  "Brazzaville Port, Congo",
  "Pointe-Noire Port, Congo",
  "Kinshasa ICD, DRC",
  "Luanda Port, Angola",
  "Lobito Port, Angola",
  "Namibe Port, Angola",
  "Windhoek ICD, Namibia",
  "Walvis Bay Port, Namibia",
  "Lubango ICD, Angola",
  "Harare ICD, Zimbabwe",
  "Bulawayo ICD, Zimbabwe",
  "Lusaka ICD, Zambia",
  "Ndola ICD, Zambia",
  "Kitwe ICD, Zambia",
  "Lilongwe ICD, Malawi",
  "Blantyre ICD, Malawi",
  "Dodoma ICD, Tanzania",
  "Kigali ICD, Rwanda",
  "Bujumbura ICD, Burundi",
  "Kampala ICD, Uganda",
  "Entebbe ICD, Uganda",
  "Juba ICD, South Sudan",
  "Bangui ICD, Central African Republic",
  "N'Djamena ICD, Chad",
  "Niamey ICD, Niger",
  "Agadez ICD, Niger",
  "Bissau Port, Guinea-Bissau",
  "Praia Port, Cape Verde",
  "Sao Tome Port, Sao Tome and Principe",
  "Libreville Port, Gabon",
  "Port-Gentil Port, Gabon",
  "Malabo Port, Equatorial Guinea",
  "Douala Port, Cameroon",
  "Yaounde ICD, Cameroon",
  "Bamenda ICD, Cameroon",
  "Yaounde ICD, Cameroon",
  "Garoua ICD, Cameroon",
  "Maroua ICD, Cameroon",
  "Ngaoundere ICD, Cameroon",
  "Bertoua ICD, Cameroon",
  "Ebolowa ICD, Cameroon",
  "Kribi Port, Cameroon",
  "Limbe Port, Cameroon",
  "Tiko Port, Cameroon",
  "Victoria Port, Cameroon",
  "Buea ICD, Cameroon",
  "Douala ICD, Cameroon",
  "Edea ICD, Cameroon",
  "Nkongsamba ICD, Cameroon",
  "Bafoussam ICD, Cameroon",
  "Dschang ICD, Cameroon",
  "Foumban ICD, Cameroon",
  "Bamenda ICD, Cameroon",
  "Kumbo ICD, Cameroon",
  "Wum ICD, Cameroon",
  "Nkambe ICD, Cameroon",
  "Fundong ICD, Cameroon",
  "Kumbo ICD, Cameroon",
  "Bali ICD, Cameroon",
  "Mbengwi ICD, Cameroon",
  "Ndop ICD, Cameroon",
  "Bamenda ICD, Cameroon",
  "Santa ICD, Cameroon",
  "Njinikom ICD, Cameroon",

  // Asia – Major Airports
  "Chennai International Airport, India",
  "Mumbai Chhatrapati Shivaji Maharaj International Airport, India",
  "Delhi Indira Gandhi International Airport, India",
  "Bengaluru Kempegowda International Airport, India",
  "Hyderabad Rajiv Gandhi International Airport, India",
  "Kolkata Netaji Subhas Chandra Bose International Airport, India",
  "Singapore Changi Airport, Singapore",
  "Dubai International Airport, UAE",
  "Abu Dhabi International Airport, UAE",
  "Doha Hamad International Airport, Qatar",
  "Kuwait International Airport, Kuwait",
  "Bahrain International Airport, Bahrain",
  "Muscat International Airport, Oman",
  "Karachi Jinnah International Airport, Pakistan",
  "Lahore Allama Iqbal International Airport, Pakistan",
  "Dhaka Hazrat Shahjalal International Airport, Bangladesh",
  "Colombo Bandaranaike International Airport, Sri Lanka",
  "Kathmandu Tribhuvan International Airport, Nepal",
  "Male Velana International Airport, Maldives",
  "Bangkok Suvarnabhumi Airport, Thailand",
  "Phuket International Airport, Thailand",
  "Ho Chi Minh City Tan Son Nhat International Airport, Vietnam",
  "Hanoi Noi Bai International Airport, Vietnam",
  "Jakarta Soekarno-Hatta International Airport, Indonesia",
  "Surabaya Juanda International Airport, Indonesia",
  "Kuala Lumpur International Airport, Malaysia",
  "Penang International Airport, Malaysia",
  "Singapore Seletar Airport, Singapore",
  "Hong Kong International Airport, Hong Kong",
  "Shanghai Pudong International Airport, China",
  "Beijing Capital International Airport, China",
  "Shenzhen Bao'an International Airport, China",
  "Guangzhou Baiyun International Airport, China",
  "Tokyo Narita International Airport, Japan",
  "Tokyo Haneda International Airport, Japan",
  "Osaka Kansai International Airport, Japan",
  "Nagoya Chubu Centrair International Airport, Japan",
  "Sapporo New Chitose Airport, Japan",
  "Busan Gimhae International Airport, South Korea",
  "Seoul Incheon International Airport, South Korea",
  "Taipei Taoyuan International Airport, Taiwan",
  "Kaohsiung International Airport, Taiwan",
  "Manila Ninoy Aquino International Airport, Philippines",

  // Africa – Major Airports
  "Johannesburg O.R. Tambo International Airport, South Africa",
  "Cape Town International Airport, South Africa",
  "Durban King Shaka International Airport, South Africa",
  "Nairobi Jomo Kenyatta International Airport, Kenya",
  "Mombasa Moi International Airport, Kenya",
  "Addis Ababa Bole International Airport, Ethiopia",
  "Lagos Murtala Muhammed International Airport, Nigeria",
  "Abuja Nnamdi Azikiwe International Airport, Nigeria",
  "Accra Kotoka International Airport, Ghana",
  "Dakar Blaise Diagne International Airport, Senegal",
  "Casablanca Mohammed V International Airport, Morocco",
  "Marrakesh Menara Airport, Morocco",
  "Tunis Carthage International Airport, Tunisia",
  "Algiers Houari Boumediene Airport, Algeria",
  "Cairo International Airport, Egypt",
  "Alexandria Borg El Arab Airport, Egypt",
  "Entebbe International Airport, Uganda",
  "Kigali International Airport, Rwanda",
  "Dar es Salaam Julius Nyerere International Airport, Tanzania",
  "Harare Robert Gabriel Mugabe International Airport, Zimbabwe",
  "Maputo International Airport, Mozambique",
  "Luanda Quatro de Fevereiro International Airport, Angola",
];
